version: '3.8'
services:
  product-api:
    build: ./product-api
    ports:
      - "5001:5000"  # Expose sur un port différent pour éviter les conflits
    networks:
      - cloudshop-network

  order-api:
    build: ./order-api
    ports:
      - "5002:5000"
    networks:
      - cloudshop-network

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"  # Le frontend sera accessible sur http://localhost:5000
    depends_on:
      - product-api
      - order-api
    networks:
      - cloudshop-network

networks:
  cloudshop-network:
    driver: bridge