# kubernetes/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: product-api-service
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 5000  # Port du service
      targetPort: 5000  # Port du conteneur
---
apiVersion: v1
kind: Service
metadata:
  name: order-api-service
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Pour accéder au frontend depuis l'extérieur
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port externe
      targetPort: 5000  # Port du conteneur Flask